### ISSUE TITLE
CdnRequest::all() should be compatible with Request::all($keys = NULL)

### ISSUE THREAD

**Issue by ellalderton** [nodes-php/assets#31]
Laravel 5.5 is throwing the following error:
Declaration of Nodes\Assets\Http\Requests\CdnRequest::all() should be compatible with Illuminate\Http\Request::all($keys = NULL).

CdnRequest's all() method should have parameters of ($keys = NULL)

**Comment by Casperhr** [comment]
Feel free to PR it, I can make a release fast
